### PR TITLE
Optee updates from upstream

### PR DESCRIPTION
**Pull request by jenswi-linaro**
These commits are already part of Linux v6.8-rc1 and will be automatically included when we rebase this branch on v6.8, but until that release, it would be convenient to have them available here.

### CODE REVIEW

**Comment by jforissier** [comment]
@jenswi-linaro agreed. I'll let the CI run as a matter of course then I'll merge this.

**Comment by jenswi-linaro** [comment]
Good idea, it looks like some patch I'm depending on might be missing. :-)

**Comment by jenswi-linaro** [comment]
The "optee" branch is currently based on v6.6, but some of these patches depend on v6.7.

**Comment by jenswi-linaro** [comment]
I've pushed a `wip/optee-v6.7` to this repository and rebased the pull request against that branch.
Once CI is happy we can merge this into that brach. I suppose that after that we can also make the main `optee` branch use what's in `wip/optee-v6.7`.

**Comment by jenswi-linaro** [comment]
CI has passed.

**Pull request merged**
