### PR TITLE
staging/ion: ARM64 supports ION_UNMAPPED_HEAP

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by etienne-lms** [comment]
Fails when unmapped heap is not enabled => to fix

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (qemu_virt, qemu_armv8)`

**Comment by jockebech** [comment]
`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by etienne-lms** [comment]
Tags applied.
This change is required to test OP-TEE/SDP (xtest) on qemu_armv8.

**Pull request merged**
