### PR TITLE
staging: android: ion: Fix unmapped heap conditional support

### PR DESCRIPTION
**Pull request by glneo**
Unmapped heaps were enabled by default when ION was enabled, this
behavior was changed when unmapped heap support was made conditional
on architecture. Make the Kconfig symbol enabled by default to fix
this.

Fixes: 4a8535ac19d5 ("staging/ion: CONFIG_ION_UNMAPPED_HEAP conditions unmapped heap")
Signed-off-by: Andrew F. Davis <afd@ti.com>

### CODE REVIEW

**Comment by vchong** [comment]
[4a8535a](https://github.com/linaro-swg/linux/commit/4a8535ac19d509cc210796664ee9bfb828b5d648) is "staging/ion: condition unmapped heap to supported architectures". In any case yea the [4.9](https://github.com/linaro-swg/linux/blob/optee-v4.9-20171018/drivers/staging/android/ion/Kconfig#L59) branch has the default set to `y` as well.

**Comment by glneo** [comment]
Yes, it looks like "staging/ion: condition unmapped heap to supported architectures" is the correct name for the patch this fixes. "staging/ion: CONFIG_ION_UNMAPPED_HEAP conditions unmapped heap" is a similar patch that seems correct but unfortunately it is the other, less correct, version that was put on the optee topic branch we integrate, breaking our SDP.

Also the 4.9 "branch" you reference looks like just a tag, and the patches appear on no real branch as far as I can tell.

**Comment by vchong** [comment]
>  Also the 4.9 "branch" you reference looks like just a tag, and the patches appear on no real branch as far as I can tell.

Right. Sorry for the confusion. The 4.9 "branch" used to be the previous `optee` branch that was backed up with the tag it has now.

What kernel version is your optee topic branch based on? The current SDP patches (on `optee` branch) are based on 4.12, while the previous SDP patches (on the 4.9 tag) were based on 4.9.

**Comment by etienne-lms** [comment]
My fault. Looks there is no issue default enabling a configuration.
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Pull request closed without merging**
