### PR TITLE
Infrastructure to support GP socket

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Adds support for asynchronous supplicant requests

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Rebased

**Comment by jenswi-linaro** [comment]
Rebased

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>` (1st and 2nd commits)
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>` (3rd commit)
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260 pager=y/n)`

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
