### PR TITLE
system thread

### PR DESCRIPTION
**Pull request by jenswi-linaro**
I intend to add these patches to linux-next after the merge window has closed and then if everything still is OK after a few weeks I'll send a pull request to arm-soc for v6.8.

### CODE REVIEW

**Comment by jforissier** [comment]
Sounds like a good idea :) I will merge this as soon as CI completes successfully.

**Comment by jforissier** [comment]
> I will merge this as soon as CI completes successfully.

Well it seems this won't happen... IBART is not happy, @jbech-linaro any idea what's happening in the post clone phase?

**Comment by jockebech** [comment]
> > I will merge this as soon as CI completes successfully.
> 
> Well it seems this won't happen... IBART is not happy, @jbech-linaro any idea what's happening in the post clone phase?

Suspecting a timeout of some sort, I'll try to check that the local cache is up-to-date and then I'll re-run it.

**Comment by jockebech** [comment]
It's getting a timeout when trying to get Jens' remote. 
```
DEBUG] do_pexpect():91   Expecting (exp): ['\r\n0\r\nIBART', <class 'pexpect.exceptions.TIMEOUT'>, '\\r\\n[^0]\\d*\\r\\nIBART'] (timeout=3, error=1)
[DEBUG] do_pexpect():94   Got: 0 (value >= 1 is considered an error)
[DEBUG] start_job():255
[DEBUG] get_yaml_cmd():41   cmd: git remote update, exp: None, chkret: y, timeout: 60
[DEBUG] do_pexpect():53   Sending: git remote update
[DEBUG] do_pexpect():91   Expecting (exp): ['\r\n0\r\nIBART', <class 'pexpect.exceptions.TIMEOUT'>, '\\r\\n[^0]\\d*\\r\\nIBART'] (timeout=60, error=1)
[DEBUG] do_pexpect():94   Got: 1 (value >= 1 is considered an error)
[ERROR] start_job():261   job type: post_clone failed!
```
This is a Linux kernel remote, that eventually can be pretty big. We only have a 10Mbps connection, so that's likely why it timeout. I'll experiment with increasing the timeout from 60 second to .... a lot more. I'll probably revert it back again later on. Stay tuned.

**Pull request merged**
