### PR TITLE
Benchmark fixes

### PR DESCRIPTION
**Pull request by jforissier**
A couple of minor fixes. Should I post patch number 2 ("tee: add forward declaration for struct device") to the LKML?

### CODE REVIEW

**Comment by jockebech** [comment]
Looks good to me, I don't know the preference in kernel for cases like this. I.e., include vs forward declaration. Regardless that I think it's a patch that should be sent upstream.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
>  I don't know the preference in kernel for cases like this. I.e., include vs forward declaration.

There is no clear-cut answer from the source at least:

```
linux/include $ git grep -E "#include <linux/(platform_|)device.h>" | wc -l
195
linux/include $ git grep "struct device;" | wc -l
112
```

I suppose it depends on whether the `.h` can be useful on its own (without `device.h` or `platform_device.h`).

**Comment by jenswi-linaro** [comment]
Looks good to me, please post ("tee: add forward declaration for struct device") on LKML and the tee-dev list.

**Comment by jforissier** [comment]
Updated first commit with "Fixes:" tag, applied @jbech-linaro's R-b: and @jenswi-linaro's Acked-by:.

FYI: http://lists.infradead.org/pipermail/linux-arm-kernel/2017-May/509790.html

**Pull request closed without merging**
