### PR TITLE
Update with patches from upstream

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jockebech** [comment]
`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
After merging that, I think we should rebase onto a more recent kernel (~~we have v4.12 if I'm not mistaken~~ **Edit:** no, was v4.18 actually). v4.19+ will allow us to drop the HiKey960 fork.

Should we pick v4.19? Or v4.20-rc1?

**Comment by jenswi-linaro** [comment]
Tag applied on `"upstream-tee-subsys-patches.txt: patches up to v4.20-rc1"` only since I'd like to keep the other commit messages as is.

**Comment by jenswi-linaro** [comment]
I'd vote for v4.19

**Comment by jockebech** [comment]
I think I'd also go for a full release number if we can avoid using a rc-number directly (so it depends on your HiKey 960 stuff here I'd say).

**Comment by jforissier** [comment]
Yeah HiKey960 works fine with v4.19. Let's avoid the rc.

**Comment by jenswi-linaro** [comment]
Doing rebases between full releases aren't very painful, so I guess if we do v4.19 now and v4.20 when that's out later it shouldn't be that much extra work.

**Comment by jforissier** [comment]
FYI - branch optee of linaro-swg/linux rebased onto v4.19. Previous tip saved as tag optee-v4.18-20181105 and branch branch-optee-v4.18-20181105.

**Pull request merged**
