### PR TITLE
dts: stm32mp13: upgrade for SCMI and async notif support

### PR DESCRIPTION
**Pull request by etienne-lms**
Update STMP32MP13 DT bindings and device tree files from v6.6 for SCMI and async notif support.

### CODE REVIEW

**Comment by jforissier** [comment]
Wouldn't you prefer that I rebase the `optee` branch onto v6.6 instead? I assume that would also make #116 irrelevant.

**Comment by etienne-lms** [comment]
Rebasing from v6.2 to v6.6 is definitely a nice option.

**Comment by jforissier** [comment]
OK, I will rebase then. It has to be done sooner or later anyways. Thanks!

**Comment by jforissier** [comment]
@etienne-lms I have locally rebased `optee` onto `v6.6`, there was only one conflict with `arch/arm/boot/dts/st/stm32mp157c-ed1.dts` which I have hopefully resolved properly :wink: could you please try branch `wip/optee-v6.6` before I switch `optee` to that? Thanks!

**Comment by etienne-lms** [comment]
I'll today and tell you. Thanks.

**Comment by etienne-lms** [comment]
@jforissier, all good to me for your `wip/optee-v6.6` branch tip. Thanks.

**Comment by jforissier** [comment]
> @jforissier, all good to me for your `wip/optee-v6.6` branch tip. Thanks.

`optee` branch updated. I suppose this can be closed now.

**Comment by etienne-lms** [comment]
Closing since rebasing on v6.6 does the jobs.

**Pull request closed without merging**
