### PR TITLE
Sync v15 and v16 patch sets

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jforissier** [comment]
LGTM, tested successfully on HiKey.

**Comment by jenswi-linaro** [comment]
So the question is, do we want to merge this before or after the release.
I'd prefer before since this is the equivalence of what's in the git pull request I sent to Arnd.

**Comment by jockebech** [comment]
Please go a head and merge it before the release if that is what you recommend Jens.

**Comment by jforissier** [comment]
Agreed.

**Pull request merged**
