### PR TITLE
V11 feedback

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Addresses comments from  Andrew F. Davis on the V11 patch set.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
@glneo, please have a look, we can perhaps save one iteration on the mailing list.

**Comment by jenswi-linaro** [comment]
Does anyone else have feedback or is this what I should post in the next patch set?

**Comment by jforissier** [comment]
LGTM

**Comment by jockebech** [comment]
No additional comments from my side.

**Comment by jenswi-linaro** [comment]
Let's merge this then.

**Pull request merged**
