### PR TITLE
tee: apply v12 delta

### PR DESCRIPTION
**Pull request by jockebech**
Applies the v12 of the generic TEE subsystem patch set.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Looks good to me, but then it's my commit also. :-)

**Comment by jforissier** [comment]
I guess we can merge this as-is.
Why doesn't Rpi3 use our main optee branch? (linaro-swg/linux optee).

**Comment by jockebech** [comment]
RPi3 kernel branch is based on yet another fork that adds AArch64 bit support for the RPi3 (i.e, there are no official AArch64 patches in mainline kernel for RPi3).

**Comment by jforissier** [comment]
Ah, yes, that's an obvious limitation ;) Thanks. I'll merge this now.

**Pull request merged**
